insert into data_set (data_set_id,data_set_name) values (1,'Colorado Plains');
insert into data_set (data_set_id,data_set_name) values (2,'Colorado Mountains');
insert into data_set (data_set_id,data_set_name) values (3,'Northeast Ohio');
insert into data_set (data_set_id,data_set_name) values (4,'Colorado (Gunnbarrel Hill)');
insert into data_set (data_set_id,data_set_name) values (5,'Colorado (Fritz Peak)');
insert into data_set (data_set_id,data_set_name) values (6,'Colorado (Golden)');
insert into data_set (data_set_id,data_set_name) values (7,'Colorado (Longmont)');
insert into data_set (data_set_id,data_set_name) values (8,'Colorado Plains (KLIR)');
insert into data_set (data_set_id,data_set_name) values (9,'Colorado Mountains (KLIR)');
insert into data_set (data_set_id,data_set_name) values (10,'Wyoming');
insert into data_set (data_set_id,data_set_name) values (11,'Idaho');
insert into data_set (data_set_id,data_set_name) values (12,'Washington');
insert into data_set (data_set_id,data_set_name) values (13,'Virginia');
insert into data_set (data_set_id,data_set_name) values (14,'Hadsund');
insert into data_set (data_set_id,data_set_name) values (15,'Hjorring');
insert into data_set (data_set_id,data_set_name) values (16,'Jerslev');
insert into data_set (data_set_id,data_set_name) values (17,'Mjels');
insert into data_set (data_set_id,data_set_name) values (18,'Ravnstru');
insert into data_set (data_set_id,data_set_name) values (19,'Arizona');
insert into data_set (data_set_id,data_set_name) values (20,'FCC');
insert into data_set (data_set_id,data_set_name) values (21,'Montana');
